### ISSUE TITLE
Power consumption data

### ISSUE THREAD

**Issue by amih77** [mluggy/electricity-plan-analyzer#1]
Hi, thanks a lot for the project! It looks like the power consumption data api is down. Is there a workaround?

**Comment by mluggy** [comment]
Hi, the URL changed slightly, try https://www.iec.co.il/consumption-info-menu/remote-reading-info

The link to request the annual consumption is at the bottom.

<img width="557" alt="image" src="https://github.com/user-attachments/assets/948e753c-88c9-41a3-a73b-aaf88b4a458c">
